#!/bin/bash

set -e
rm -rf dist
git fetch --all
python3 -m build

while true; do

read -p "Do you want to publish this package ? (y/n) " yn

case $yn in 
	[yY] ) echo publishing to pypi;
		break;;
	[nN] ) echo exiting;
		exit;;
	* ) echo invalid response;;
esac

done

python3 -m twine upload dist/*
